import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { AppSidebar } from "@/components/app-sidebar";
import { CommandPaletteProvider } from "@/components/command-palette";
import { SiteHeader } from "@/components/site-header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
        >
          {/* h-svh + min-h-0 (the target's own wrapper classes) constrain the
              height chain so the inner overflow-auto container scrolls, as on
              the target — without it the document grows instead. */}
          <CommandPaletteProvider>
          <SidebarProvider className="h-svh min-h-0">
            <AppSidebar />
            <SidebarInset className="min-h-0 overflow-hidden">
              <SiteHeader />
              <div className="flex flex-1 flex-col gap-4 overflow-auto p-4 *:shrink-0">
                {children}
              </div>
            </SidebarInset>
          </SidebarProvider>
          </CommandPaletteProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
